### ISSUE TITLE
miix520 i5 8g 256g 安装求助

### ISSUE THREAD

**Issue by wangxiangshuai** [acai66/lenovo-miix-520-hackintosh-10.14-CLOVER#1]
你可以给一个安装包么，我用你的引导文件，一直不能安装成功，版本是10.14，希望能得到你帮助

**Comment by acai66** [comment]
安装时，先屏蔽核显，具体做法是启动到clover界面，按字母o，找到graphics开头的选项，勾选里面的inject intel ，再修改*-platfrom-id为0x12345678，再esc键回clover主界面，启动安装，等安装好进入到桌面后，运行kext utility，输入密码，等待操作完成，quit，再不屏蔽显卡启动就好了。

**Comment by acai66** [comment]
已更新readme，添加常见问题解答。
