### ISSUE TITLE
MIIX520 安装完成，替换CLOVER后到50%进度不走了

### ISSUE THREAD

**Issue by EvilZabanya** [acai66/lenovo-miix-520-hackintosh-10.14-CLOVER#3]
使用网上原版10.14.3系统+整合版CLOVER的dmg镜像，安装完成后可以正常进系统，替换大佬你的CLOVER以后（直接把你的CLOVER放入硬盘efi文件夹，添加CLOVER引导），开机CLOVER界面正常，选择Mac导引后开机进度走到一半就卡住了，求助！如果重新用U盘引导通用CLOVER可以进mac

**Comment by EvilZabanya** [comment]
先屏蔽核显，具体做法是启动到clover界面，按字母o，找到graphics开头的选项，勾选里面的inject intel ，再修改*-platfrom-id为0x12345678，再esc键回clover主界面，启动安装，等安装好进入到桌面后，运行kext utility，输入密码，等待操作完成，quit，再不屏蔽显卡启动就好了。

使用该操作屏蔽核显后成功进入系统，kext utility运行后正常进入系统，核显显存1.5G，现在还有个无线网卡好像有问题，研究中

**Comment by acai66** [comment]
intel的无线网卡无解的，拆机换联想版bcm94352z吧

**Comment by EvilZabanya** [comment]
大佬，目前USB网卡（RTL8192EU）自己找驱动搞定了
蓝牙连小米无线鼠标总是连不上（usb位置被usb网卡占了，不过好像这个鼠标蓝牙也连不上正经的MBA）
使用lightroom无法合成hdr，一合成就提示出现了内部错误，无法从xxx导入最终的合并结果

**Comment by acai66** [comment]
intel的蓝牙多数是免驱的，要真有问题，好像也没有什么好的解决办法的，usb网卡是不被推荐使用的，建议换内置网卡，原生wifi与蓝牙都能用的网卡，那个什么软件，你搜搜看这软件与黑苹果有没有关系，一般的软件是与黑苹果无关的，现在只要显存1536m，界面不卡，显卡就应该是完美驱动的，就有可能是软件本身或别的问题

**Comment by acai66** [comment]
已更新readme，添加常见问题解答。
