### ISSUE TITLE
Installer reboot and crash at 2 mins left.

### ISSUE THREAD

**Issue by yong2222** [acai66/lenovo-miix-520-hackintosh-10.14-CLOVER#4]
I can enter the installer but it stops at 2 min and reboots right away. And then I cannot enter the mac again. Maybe it is the problem of the sata mode. However, I cannot find the option to change my storage mode to ahci. How should I do?

**Comment by acai66** [comment]
miix 520 is only support ahci mode,so you dont worry about sata mode,Where did you get the macos image?I have tested several versions of macos,and there is no any problem.

**Comment by yong2222** [comment]
I used one that you mentioned, 黑果小兵 with clover 4674 version. And my laptop is actually i7-8550u 8gb 512gb, it seems that some of the kexts are not working properky because of the different hardware.

**Comment by yong2222** [comment]
After all, I have got mac booting on my device, but without your kexts. So I cannot use touch screen and sound card at all. Do you have any solutions?

**Comment by acai66** [comment]
> After all, I have got mac booting on my device, but without your kexts. So I cannot use touch screen and sound card at all. Do you have any solutions?

both i7 and i5 can use this clover,there is no different hardware but cpu,and No special configuration is required for the CPU

**Comment by yong2222** [comment]
Umm.. then what do you think about the problem? When I use your kexts I get applei2ccontroller input time out and ps2controller fsever time out.. :( I could send you the boot screen of verbose mode if you wish to help me out.

**Comment by acai66** [comment]
remove AppleIntelLpssI2C.kext and AppleIntelLpssI2CController.kext.
When removing those 2 kexts, you should also remove AppleHPM.kext, since it has dependencies on the I2C kexts.
After that, rebuild your kextcache and reboot.

**Comment by yong2222** [comment]
Then I should install the mac at the very first time without your kexts? And then do the things you told me and put those kexts after the first boot? Sorry I'm new to the mac environment.. :(

**Comment by yong2222** [comment]
Also I cannot find the files you mentioned in my usb..

**Comment by acai66** [comment]
in your macos volume \System\Library\Extensions,

**Comment by yong2222** [comment]
Oh so I have to install first because my windows computer does not work on the mac files.
Then I have to complete the installation first and change the kexts.

**Comment by acai66** [comment]
you can rename /efi/clover/kext/other/voodooi2c.kext to voodooi2c for disable voodooi2c driver,and restore this driver after you remove applei2ccon...

**Comment by yong2222** [comment]
only voodooi2c that one or other related things too? I see lots of things contain voodoo in name.

**Comment by acai66** [comment]
the core kext is the voodooi2c.kext ,

**Comment by yong2222** [comment]
Ok I have one more question. Should I put the clover folder to overwrite, or just delete the original clover folder in usb and put only your clover folder?

**Comment by acai66** [comment]
delete

**Comment by yong2222** [comment]
Ok thanks

**Comment by yong2222** [comment]
Thanks for your help. I almost went to success. But the thing is, I cannot boot clover without usb even if I installed the clover bootloader to my ssd. I can see efi partition has clover boot files, but somehow it keeps booting windows 10 without having clover boot screen.( Windows bootloader is stronger than Clover bootloader.) Can you help me out?

**Comment by yong2222** [comment]
Oh.. and my touchscreen does not work.. (I'm sure I installed voodooi2c that you offered.) Is there additional steps I have to do?

**Comment by acai66** [comment]
no,

**Comment by yong2222** [comment]
Touchscreen works well with touchpad, but somehow touchpad does not work with multitouch gestures, I see the menu with gestures but it does not function at all.

**Comment by acai66** [comment]
see this,waiting for alexandred to fix it.
https://github.com/alexandred/VoodooI2C/issues/115

**Comment by yong2222** [comment]
But my trackpad does not work too... Trackpad is also not supported? I think it should work but not mine.

**Comment by acai66** [comment]
use my modified voodooi2c.kext ,do not use official voodooi2c.kext

**Comment by yong2222** [comment]
I used kext wizard and installed it, also I put the kexts in efi and sle. Still it's not working. Am I missing something??

**Comment by acai66** [comment]
i have updated clover,fixed some patches.

**Comment by yong2222** [comment]
Still.. Some basic gestures like scroll and double click works, but extra gestures using multiple fingers not work at all. (I'm not talking about touch screen, it's touchpad.)

**Comment by acai66** [comment]
the touchpad just works like a mouse,only with basic functions,and i cant make it fully works.

**Comment by yong2222** [comment]
Then do you have some suggestions to use it better? Some settings.
