### ISSUE TITLE
长时间卡在InitScreen和ScanVolumes

### ISSUE THREAD

**Issue by ruiwei687** [acai66/lenovo-miix-520-hackintosh-10.14-CLOVER#6]
0:101  0:000  === [ GetCPUProperties ] ==================================
0:101  0:000  CPU Vendor = 756E6547 Model=806EA
0:101  0:000   The CPU supported SSE4.1
0:101  0:000  BrandString = Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
0:101  0:000   The CPU supported turbo
0:101  0:000  MSR 0x35               40008
0:101  0:000   TSC/CCC Information Leaf:
0:101  0:000    numerator     : 150
0:101  0:000    denominator   : 2
0:101  0:000   Calibrated ARTFrequency: 23974857
0:101  0:000  MSR 0xE2 before patch 1E008008
0:101  0:000  MSR 0xE2 is locked, PM patches will be turned on
0:101  0:000  MSR 0xCE              0004043D_F1011200
0:101  0:000  corrected FLEX_RATIO = 0
0:101  0:000  MSR 0x1B0             00000000
0:101  0:000  FSBFrequency = 23 MHz, DMI FSBFrequency = 100 MHz, Corrected FSBFrequency = 100 MHz
0:101  0:000  MaxDiv/MinDiv: 18.0/4
0:101  0:000  Turbo: 34/34/34/34
0:101  0:000  Features: 0xBFEBFBFF
0:101  0:000  Threads: 8
0:101  0:000  Cores: 4
0:101  0:000  FSB: 100 MHz
0:101  0:000  CPU: 400 MHz
0:101  0:000  TSC: 400 MHz
0:101  0:000  PIS: 100 MHz
0:101  0:000  ExternalClock: 25 MHz
0:101  0:000  === [ GetDevices ] ========================================
0:101  0:000  PCI (00|00:00.00) : 8086 5914 class=060000
0:101  0:000  PCI (00|00:02.00) : 8086 5917 class=030000
0:101  0:000   - GFX: Model=Intel UHD Graphics 620 (Intel)
0:101  0:000  PCI (00|00:04.00) : 8086 1903 class=118000
0:101  0:000  PCI (00|00:05.00) : 8086 1919 class=048000
0:101  0:000  PCI (00|00:13.00) : 8086 9D35 class=000000
0:101  0:000  PCI (00|00:14.00) : 8086 9D2F class=0C0330
0:101  0:000  PCI (00|00:14.02) : 8086 9D31 class=118000
0:102  0:000  PCI (00|00:14.03) : 8086 9D32 class=048000
0:102  0:000  PCI (00|00:15.00) : 8086 9D60 class=118000
0:102  0:000  PCI (00|00:15.01) : 8086 9D61 class=118000
0:102  0:000  PCI (00|00:15.02) : 8086 9D62 class=118000
0:102  0:000  PCI (00|00:15.03) : 8086 9D63 class=118000
0:102  0:000  PCI (00|00:16.00) : 8086 9D3A class=078000
0:102  0:000  PCI (00|00:17.00) : 8086 9D03 class=010601
0:102  0:000  PCI (00|00:1C.00) : 8086 9D13 class=060400
0:102  0:000  PCI (00|01:00.00) : 168C 0042 class=028000
0:102  0:000   - WIFI: Vendor=Atheros
0:102  0:000  PCI (00|00:1C.05) : 8086 9D15 class=060400
0:102  0:000  PCI (00|02:00.00) : FFFF FFFF class=FFFFFF
0:102  0:000  PCI (00|00:1D.00) : 8086 9D18 class=060400
0:102  0:000  PCI (00|07:00.00) : 144D A804 class=010802
0:102  0:000  PCI (00|00:1E.00) : 8086 9D27 class=118000
0:102  0:000  PCI (00|00:1E.03) : 8086 9D2A class=118000
0:102  0:000  PCI (00|00:1F.00) : 8086 9D4E class=060100
0:102  0:000  PCI (00|00:1F.02) : 8086 9D21 class=058000
0:102  0:000  PCI (00|00:1F.03) : 8086 9D71 class=040300
0:102  0:000  PCI (00|00:1F.04) : 8086 9D23 class=0C0500
0:102  0:000  === [ GetDefaultSettings ] ================================
0:102  0:000  Clover load options size = 0 bytes
0:124  0:021  EFI\CLOVER\config.plist loaded: Success
0:124  0:000  === [ GetListOfThemes ] ===================================
0:125  0:000  - [00]: iclover
0:125  0:000  - [01]: Simple
0:126  0:000  - [02]: SimpleThemeDark
0:127  0:001  === [ Found config plists ] ===============================
0:128  0:000  - config.plist
0:128  0:000  === [ GetEarlyUserSettings ] ==============================
0:128  0:000  timeout set to 0
0:128  0:000  Custom boot CUSTOM_BOOT_DISABLED (0x0)
0:128  0:000  FakeCPUID: 406E3
0:128  0:000  KextsToPatch: 7 requested
0:128  0:000   - [00]: IOGraphicsFamily (10.12+-第二阶段花屏补丁) :: MatchOS: 10.12.x :: BinPatch :: data len: 5
0:128  0:000   - patch disabled at config
0:128  0:000   - [01]: com.apple.driver.IOGraphicsFamily (10.14+-第二阶段花屏补丁) :: BinPatch :: data len: 5
0:128  0:000   - [02]: AppleAHCIPort (External icons patch) :: BinPatch :: data len: 8
0:128  0:000   - [03]: AppleUSBXHCIPCI (Change 15 port limit to 24 in XHCI kext 10.13) :: BinPatch :: data len: 4
0:128  0:000   - [04]: IOAHCIBlockStorage (#02 Enable TRIM for non-Apple SSDs, RehabMan) :: BinPatch :: data len: 11
0:128  0:000   - [05]: com.apple.driver.AppleIntelLpssI2C (Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar) :: PlistPatch :: data len: 5
0:128  0:000   - [06]: com.apple.driver.AppleIntelLpssI2CController (Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar) :: PlistPatch :: data len: 5
0:128  0:000  KernelToPatch: 3 requested
0:128  0:000   - [00]: Disable panic kext logging on 10.13 debug kernel (credit vit9696) :: MatchOS: 10.13.x :: data len: 6
0:128  0:000   - [01]: Disable panic kext logging on 10.13 release kernel (credit vit9696) :: MatchOS: 10.13.x :: data len: 6
0:128  0:000   - [02]: Disable panic kext logging on 10.14 release kernel (credit vit9696) :: MatchOS: 10.14.x :: data len: 6
0:128  0:000  Default theme: Simple
0:129  0:000  Custom entry boot CUSTOM_BOOT_THEME (0x0)
0:129  0:000  === [ LoadDrivers ] =======================================
0:130  0:000  Loading HFSPlus.efi  status=Success
0:135  0:004   - driver needs connecting
0:135  0:000  Loading DataHubDxe-64.efi  status=Success
0:139  0:003  Loading VirtualSmc.efi  status=Success
0:143  0:004  Loading FSInject-64.efi  status=Success
0:148  0:004  Loading ApfsDriverLoader-64.efi  status=Success
0:152  0:003   - driver needs connecting
0:152  0:000  Loading AptioMemoryFix-64.efi  status=Success
0:157  0:004  Loading NTFS-64.efi  status=Success
0:165  0:008   - driver needs connecting
0:165  0:000  Loading AudioDxe-64.efi  status=Success
0:170  0:005   - driver needs connecting
0:170  0:000  4 drivers needs connecting ...
0:171  0:000  PlatformDriverOverrideProtocol->GetDriver overriden
0:171  0:000  HFS+ driver loaded
0:171  0:000  APFS driver loaded
0:171  0:000  Searching for invalid DiskIo BY_DRIVER connects: not found, all ok
6:420  6:249  === [ InitScreen ] ========================================
6:420  0:000  Console modes reported: 8, available modes:
6:420  0:000   - [01]: 80x25
6:420  0:000   - [02]: 80x50
6:420  0:000   - [03]: 80x25
6:420  0:000   - [04]: 240x63 (current mode)
6:420  0:000   - [05]: 100x31
6:420  0:000   - [06]: 128x40
6:420  0:000   - [07]: 160x53
6:420  0:000   - [08]: 200x63
6:420  0:000  SetScreenResolution: 1920x1200 - already set
6:421  0:000  SetScreenResolution: 1920x1200 - already set
6:421  0:000  reinit: self device path=PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(1,GPT,83857A1F-6EB9-49C9-983F-C61E6DAB56F1,0x800,0x82000)
6:421  0:000  === [ GetMacAddress ] =====================================
6:421  0:000  === [ ScanSPD ] ===========================================
6:422  0:000  Scanning SMBus [8086:9D23], mmio: 0xA374C004, ioport: 0x4040, hostc: 0x11
6:433  0:010  === [ GetAcpiTablesList ] =================================
6:433  0:000  Get Acpi Tables List from RSDT:
6:433  0:000   - [00]: FACP  CB-01    len=268
6:433  0:000   - [01]: UEFI  CB-01    len=566
6:433  0:000   - [02]: UEFI  CB-01    len=66
6:433  0:000   - [03]: SSDT  CB-01    len=3442
6:433  0:000   - [04]: MSDM  CB-01    len=85
6:433  0:000   - [05]: SSDT  CB-01    len=1219
6:433  0:000   - [06]: SSDT  CB-01    len=70
6:433  0:000   - [07]: TPM2  CB-01    len=52
6:433  0:000   - [08]: SSDT  CB-01    len=12560
6:433  0:000   - [09]: SSDT  CB-01    len=16210
6:433  0:000   - [10]: SSDT  CB-01    len=2510
6:433  0:000   - [11]: ASF!  CB-01    len=165
6:433  0:000   - [12]: ASPT  CB-01    len=52
6:433  0:000   - [13]: BOOT  CB-01    len=40
6:433  0:000   - [14]: DBGP  CB-01    len=52
6:433  0:000   - [15]: HPET  CB-01    len=56
6:433  0:000   - [16]: APIC  CB-01    len=300
6:433  0:000   - [17]: MCFG  CB-01    len=60
6:433  0:000   - [18]: SSDT  CB-01    len=1303
6:433  0:000   - [19]: SSDT  CB-01    len=4577
6:433  0:000   - [20]: LPIT  CB-01    len=148
6:433  0:000   - [21]: WSMT  CB-01    len=40
6:433  0:000   - [22]: SSDT  CB-01    len=671
6:433  0:000   - [23]: SSDT  CB-01    len=838
6:433  0:000   - [24]: SSDT  CB-01    len=12290
6:433  0:000   - [25]: SSDT  CB-01    len=1310
6:433  0:000   - [26]: DBGP  CB-01    len=52
6:433  0:000   - [27]: DBG2  CB-01    len=84
6:433  0:000   - [28]: SSDT  CB-01    len=4272
6:433  0:000   - [29]: SSDT  CB-01    len=6062
6:433  0:000   - [30]: DMAR  CB-01    len=384
6:433  0:000   - [31]: FPDT  CB-01    len=68
6:433  0:000   - [32]: BGRT  CB-01    len=56
6:433  0:000  Calibrated TSC Frequency = 1798114340 = 1798MHz
6:433  0:000  === [ GetUserSettings ] ===================================
6:434  0:000  Add 1 devices:
6:434  0:000  USB FixOwnership: yes
6:434  0:000  Dropping 2 tables:
6:434  0:000   - [00]: Drop table  signature="DMAR" (52414D44)
6:434  0:000           - set table: 52414D44,                0 to drop: yes
6:434  0:000   - [01]: Drop table  signature="MATS" (5354414D)
6:434  0:000           - set table: 5354414D,                0 to drop: no
6:434  0:000   - final DSDT Fix mask=0002000C
6:434  0:000  PatchesDSDT: 20 requested
6:434  0:000   - [00]: (change SAT0 to SATA) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:434  0:000   - [01]: (change HECI to IMEI) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:434  0:000   - [02]: (change GFX0 to IGPU) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:434  0:000   - [03]: (change Method(GPRW,2,N) to XPRW, pair with SSDT-GPRW.aml) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:434  0:000   - [04]: (change _OSI to XOSI, pair with SSDT-XOSI.aml) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:434  0:000   - [05]: (change _BIF to TBIF for battery status) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:434  0:000   - [06]: (change _BST to TBST for battery status) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:434  0:000   - [07]: (change GSBI to GSB0 for battery status) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:434  0:000    patch disabled at config
6:434  0:000   - [08]: (MAMR TO MAM00) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:434  0:000    patch disabled at config
6:434  0:000   - [09]: (MAMR TO MAM00) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:434  0:000    patch disabled at config
6:434  0:000   - [10]: (change HDAS to HDEF) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:434  0:000   - [11]: (change _DSM to XDSM) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:434  0:000   - [12]: (change Method(_PTS,1,N) to ZPTS, pair with SSDT-PTSWAK.aml) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:434  0:000   - [13]: (change Method(_PTS,1,S) to ZPTS, pair with SSDT-PTSWAK.aml) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:435  0:000   - [14]: (change Method(_WAK,1,N) to ZWAK, pair with SSDT-PTSWAK.aml) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:435  0:000   - [15]: (change Method(_WAK,1,S) to ZWAK, pair with SSDT-PTSWAK.aml) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:435  0:000   - [16]: (change EHC1 to EH01) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:435  0:000   - [17]: (change EHC2 to EH02) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:435  0:000   - [18]: (rename h_ec to ec) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:435  0:000   - [19]: (change _LID to LIDX,pair with ssdt-bat0-lid) lenToFind: 5, lenToReplace: 5, Target Bridge: <null string>
6:435  0:000  PluginType: 1
6:435  0:000  Using ProductName from config: MacBookPro13,1
6:435  0:000  Using latest BiosVersion from clover
6:435  0:000  BiosVersion: MBP131.88Z.F000.B00.1902141510
6:435  0:000  BiosReleaseDate: 02/14/2019
6:435  0:000  Using EfiVersion from config: 228.0.0.0.0
6:435  0:000  Using FirmwareFeatures from config: 0xFC0FE137
6:435  0:000  Using FirmwareFeaturesMask from config: 0xFF1FFF3F
6:435  0:000  Board-ID set from config as Mac-473D31EABEB93F9B
6:435  0:000  BoardType: 0xA
6:435  0:000  ChassisType: 0x9
6:435  0:000  === [ GetEfiBootDeviceFromNvram ] =========================
6:436  0:000   - efi-boot-device-data: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,199945A990E01A3EAE372757CF0D0020)
6:436  0:000    - Volume: 'PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,199945A990E01A3EAE372757CF0D0020)'
6:436  0:000    - LoaderPath: '<null string>'
6:436  0:000    - Guid = 0FBDDB9F-2147-4425-93E5-1F60688458EB
6:437  0:000  === [ Found DSDT tables ] =================================
12:987  6:550  === [ ScanVolumes ] =======================================
12:987  0:000  Found 10 volumes with blockIO
12:987  0:000  - [00]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)
12:987  0:000  - [01]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(1,GPT,83857A1F-6EB9-49C9-983F-C61E6DAB56F1,0x800,0x82000)
12:988  0:000          Result of bootcode detection: bootable Windows (vista,win)
12:988  0:000          This is SelfVolume !!
12:988  0:000  - [02]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(2,GPT,CA94D3AE-5090-4844-8FF7-25731E68D6A3,0x82800,0x8000)
12:989  0:000  - [03]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(3,GPT,588C4507-BB37-415B-AEC7-C3004D1B53AF,0x8A800,0xC800000)
12:989  0:000          Result of bootcode detection: bootable Windows (vista,win)
12:989  0:000  - [04]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(4,GPT,756BDD18-C97C-4208-9B65-CD761A0638CF,0xC88A800,0xAE74800)
12:990  0:000          Result of bootcode detection: bootable Windows (vista,win)
12:990  0:000  - [05]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)
12:991  0:000          Result of bootcode detection: bootable unknown (legacy)
12:991  0:000  - [06]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,32845D5773CD504B8145A6426BC72DBB)
12:991  0:000  - [07]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,199945A990E01A3EAE372757CF0D0020)
12:992  0:000  - [08]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,D84C893CE0DA4B4C859062EE74706ABF)
12:992  0:000  - [09]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,895D1462E6D90F45AC0ADC74C4EFF00C)
12:994  0:001  found 2 handles with audio
12:994  0:000  got index=0
12:994  0:000  got volume 70
12:994  0:000  === [ InitTheme ] =========================================
12:994  0:000  use daylight theme
13:060  0:066  Using theme 'Simple' (EFI\CLOVER\themes\Simple)
13:060  0:000  OS main and drive as badge
13:069  0:008  file sound read: sound.wav Not Found
13:076  0:006  Loading font from ThemeDir: Success
13:078  0:001  theme inited
13:078  0:000  Chosen theme Simple
13:078  0:000  found boot-args in NVRAM:, size=1
13:078  0:000  after NVRAM boot-args=darkwake=0 abm_firstpolldelay=16000 -lilubetaall kext-dev-mode=1 -no_compat_check lilucpu=8
13:078  0:000  === [ Dump SMC keys from NVRAM ] ==========================
13:078  0:000  found AppleSMC protocol
13:099  0:020  === [ AddCustomEntries ] ==================================
13:099  0:000  Custom entry 0 Title:"Windows" Path:"\EFI\Microsoft\Boot\bootmgfw.efi" Options:"-s -h" Type:7 Flags:0x0 matching Volume:"83857A1F-6EB9-49C9-983F-C61E6DAB56F1"
13:099  0:000      Checking volume "SYSTEM_DRV" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(1,GPT,83857A1F-6EB9-49C9-983F-C61E6DAB56F1,0x800,0x82000)) ... match!
13:104  0:005  Custom settings: <null string>.plist will  be applied
13:105  0:000      Checking volume "Windows" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(3,GPT,588C4507-BB37-415B-AEC7-C3004D1B53AF,0x8A800,0xC800000)) ... skipped
13:105  0:000      Checking volume "LENOVO" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(4,GPT,756BDD18-C97C-4208-9B65-CD761A0638CF,0xC88A800,0xAE74800)) ... skipped
13:105  0:000      Checking volume "Preboot" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,32845D5773CD504B8145A6426BC72DBB)) ... skipped
13:105  0:000      Checking volume "MacOS" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,199945A990E01A3EAE372757CF0D0020)) ... skipped
13:105  0:000      Checking volume "Recovery" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,D84C893CE0DA4B4C859062EE74706ABF)) ... skipped
13:105  0:000      Checking volume "VM" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,895D1462E6D90F45AC0ADC74C4EFF00C)) ... skipped
13:105  0:000  Custom entry 1 Title:"MacOS" Path:"\System\Library\CoreServices\boot.efi" Type:1 Flags:0x2 matching Volume:"0FBDDB9F-2147-4425-93E5-1F60688458EB"
13:105  0:000      Checking volume "SYSTEM_DRV" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(1,GPT,83857A1F-6EB9-49C9-983F-C61E6DAB56F1,0x800,0x82000)) ... skipped
13:105  0:000      Checking volume "Windows" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(3,GPT,588C4507-BB37-415B-AEC7-C3004D1B53AF,0x8A800,0xC800000)) ... skipped
13:105  0:000      Checking volume "LENOVO" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(4,GPT,756BDD18-C97C-4208-9B65-CD761A0638CF,0xC88A800,0xAE74800)) ... skipped
13:105  0:000      Checking volume "Preboot" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,32845D5773CD504B8145A6426BC72DBB)) ... skipped because path does not exist
13:106  0:000      Checking volume "MacOS" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,199945A990E01A3EAE372757CF0D0020)) ... match!
13:134  0:028      hibernated: set as never
13:136  0:002          [!] Icon 18 (icons\vol_internal_apfs.icns) not found (path: EFI\CLOVER\themes\Simple)
13:138  0:001  Custom settings: <null string>.plist will  be applied
13:143  0:004      Checking volume "Recovery" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,D84C893CE0DA4B4C859062EE74706ABF)) ... skipped because path does not exist
13:143  0:000      Checking volume "VM" (PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,895D1462E6D90F45AC0ADC74C4EFF00C)) ... skipped because path does not exist
13:143  0:000  === [ ScanLoader ] ========================================
13:143  0:000  - [01]: 'SYSTEM_DRV'
13:145  0:001          AddLoaderEntry for Volume Name=SYSTEM_DRV
13:145  0:000       skipped because path `PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(1,GPT,83857A1F-6EB9-49C9-983F-C61E6DAB56F1,0x800,0x82000)\EFI\microsoft\Boot\bootmgfw.efii` already exists for another entry!
13:197  0:052          AddLoaderEntry for Volume Name=SYSTEM_DRV
13:197  0:000          skipped because entry is hidden
13:197  0:000  - [03]: 'Windows'
13:258  0:060  - [04]: 'LENOVO'
13:319  0:060  - [06]: 'Preboot'
13:321  0:002          AddLoaderEntry for Volume Name=Preboot
13:326  0:004      hibernated: set as never
13:331  0:005          AddLoaderEntry for Volume Name=Preboot
13:393  0:061  - [07]: 'MacOS'
13:401  0:008          AddLoaderEntry for Volume Name=MacOS
13:401  0:000       skipped because path `PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,199945A990E01A3EAE372757CF0D0020)\System\Library\CoreServices\boot.efii` already exists for another entry!
13:453  0:051  - [08]: 'Recovery'
13:455  0:001          AddLoaderEntry for Volume Name=Recovery
13:515  0:060  - [09]: 'VM'
13:566  0:050  Scanning legacy ...
13:566  0:000   1: 'SYSTEM_DRV' (vista,win) add legacy
13:568  0:002   added 'Boot Windows from SYSTEM_DRV' OSType=2 Icon=vista,win
13:568  0:000   3: 'Windows' (vista,win) add legacy
13:570  0:002   added 'Boot Windows from Windows' OSType=2 Icon=vista,win
13:570  0:000   4: 'LENOVO' (vista,win) add legacy
13:572  0:002   added 'Boot Windows from LENOVO' OSType=2 Icon=vista,win
13:572  0:000  === [ AddCustomTool ] =====================================
13:574  0:001  found tool \EFI\CLOVER\tools\Shell64U.efi
13:574  0:000  Checking EFI partition Volume 1 for Clover
13:574  0:000   Found Clover
13:579  0:005  === [ GetEfiBootDeviceFromNvram ] =========================
13:579  0:000  === [ FindStartupDiskVolume ] =============================
13:579  0:000    - Volume: partition = PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,A5-50-B9-81-B4-38-25-00)\HD(5,GPT,0FBDDB9F-2147-4425-93E5-1F60688458EB,0x176FF000,0x65F4288)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,199945A990E01A3EAE372757CF0D0020)
13:579  0:000     - searching for that partition
13:579  0:000      - found entry 1. 'Boot MacOS from MacOS', Volume 'MacOS'
13:579  0:000  Boot redirected to Entry 1. 'Boot MacOS from MacOS'
13:579  0:000  DefaultIndex=1 and MainMenu.EntryCount=14
13:579  0:000  === [ StartLoader ] =======================================

**Comment by acai66** [comment]
是在加载clover界面卡住吗？扫描所有驱动器、加载主题、加载hotpatch补丁等确实会慢些，我这边并没有卡住过。

**Comment by ruiwei687** [comment]
这个和UEFI的设置会有关吗？

**Comment by acai66** [comment]
clover引导之前的日志输出已被关闭，试试新的clover。
