### ISSUE TITLE
Miix 510 可以直接上吗

### ISSUE THREAD

**Issue by onnonn** [acai66/lenovo-miix-520-hackintosh-10.14-CLOVER#8]

**Comment by acai66** [comment]
可以，我记得有老哥用我这装过

**Comment by onnonn** [comment]
> 可以，我记得有老哥用我这装过

emmmm为啥我用这个会  xv 会卡死呢

**Comment by onnonn** [comment]
还有就是您有没有配置clover的笔记什么的让我们照猫画虎呢

**Comment by onnonn** [comment]
miix510可以用了 ，就是把显卡id注入一下就可以，但是没法调分辨率和声音

**Comment by acai66** [comment]
> miix510可以用了 ，就是把显卡id注入一下就可以，但是没法调分辨率和声音

前几个版本开始，不再仿冒6代u核显，所以，miix510不能默认驱动显卡了，而且miix510可用的声卡layout id好像是28，所以，需要稍微修改下才能用，我记得只需要修改config.plist就可以了

**Comment by onnonn** [comment]
也就是说只有旧版本的clover支持6代u核显是吗，怪不得用最新的clover怎么仿冒显卡都不能调分辨率，之前的14.1对应的clover就可以调
